baseurl = "https://gpestana.com"
languageCode = "en-us"
title = "gpestana"
theme = "hugo-classic"
googleAnalytics = "ABCD"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/blog/:slug/"

[params]
    description = "gonçalo pestana (gpestana)"

[[menu.feed]]
    name = "blog/subscribe"
    url = "/index.xml"
    weight = 1

[[menu.feed]]
    name = "blog/tags"
    url = "/tags/"
    weight = 2

